on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

permissions: read-all

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_CONFIG_PAK_ENABLED: TRUE
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install ‘rprofile’
        run: cd ..; Rscript -e 'install.packages("rprofile")'

      - uses: r-lib/actions/setup-renv@v2

      - name: Build site
        run: |
         reload()
         pkgdown::build_site_github_pages(new_process = FALSE)
        shell: Rscript {0}

      - name: Deploy
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: false
          folder: docs
